steps:
  # Step 1: Install Node.js dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 3: Deploy to Google Cloud App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

# Optional: Timeout configuration for the entire build process
timeout: '600s'
