steps:
- name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo 'SECRET_KEY=${_SECRET_KEY}' > /workspace/secrets.txt
        echo 'ACCESS_TOKEN=${_ACCESS_TOKEN}' >> /workspace/secrets.txt
        echo 'TRANSACTION_ID=${_TRANSACTION_ID}' >> /workspace/secrets.txt
        echo 'USER_ID=${_USER_ID}' >> /workspace/secrets.txt
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', 'app/app.yaml']
timeout: "1600s"