steps:
- name: 'python:3.9'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export SECRET_KEY=$$SECRET_KEY
    python app/app.py
    python app/accesslink.py
  secretEnv: ['SECRET_KEY']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app/app.yaml']

availableSecrets:
  secretManager:
  - versionName: projects/736978755260/secrets/SECRET_KEY/versions/1
    env: 'SECRET_KEY'

