steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app/app.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - '-c'
    - |
      sed -i 's/%SECRET_KEY%/'$$SECRET_KEY'/g' app.yaml
      gcloud app deploy app.yaml
  secretEnv: ['SECRET_KEY']


availableSecrets:
  secretManager:
  - versionName: projects/736978755260/secrets/SECRET_KEY/versions/1
    env: 'SECRET_KEY'

