steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - '-c'
    - |
      echo "SECRET_KEY=b'"$$SECRET_KEY"'" > app/configApp.py
  secretEnv: ['SECRET_KEY']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app/app.yaml']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - '-c'
    - |
      less /workspace/app/configApp.py

availableSecrets:
  secretManager:
  - versionName: projects/736978755260/secrets/SECRET_KEY/versions/1
    env: 'SECRET_KEY'

