name: Run pytest on push

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Adjust to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest

    - name: Run pytest
      run: pytest
