name: Run pytest on push

on:
  push:
    branches:
      - '*'  # All branches
    paths:
      - '.server/**'
      - '.tests/**'
      - '.github/workflows/pytest.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install pytest

    - name: Run pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/server
        python -m pytest
