name: Run pytest on push

on:
  push:
    branches:
      - '*'  # All branches
    paths:
      - '.server/**'
      - '.tests/**'
      - '.github/workflows/pytest.yml'

jobs:
  test:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/274493427411/locations/global/workloadIdentityPools/syke-github-pool/providers/syke-github-provider'
          service_account: 'gcp-github-actions@syke-407909.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set up Google Application Credentials
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/${{ steps.auth.outputs.credentials_file }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install pytest
    

      - name: Run pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/server
          python -m pytest
