- name: Install Dependencies
    run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest
- name: Run Tests
      run: |
        python -m pytest